services:
  app-aggregator:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: tgtime-aggregator
    ports:
      - "${HTTP_PORT:-8081}:8081"
      - "${GRPC_PORT:-8082}:8082"
    networks:
      - tgtime-aggregator-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1s

networks:
  tgtime-aggregator-network:
    driver: bridge