// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: aggregatorsvc.proto

package aggregatorsvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Seconds    int64  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	RouterId   int64  `protobuf:"varint,3,opt,name=routerId,proto3" json:"routerId,omitempty"`
}

func (x *CreateTimeRequest) Reset() {
	*x = CreateTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeRequest) ProtoMessage() {}

func (x *CreateTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeRequest.ProtoReflect.Descriptor instead.
func (*CreateTimeRequest) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTimeRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *CreateTimeRequest) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *CreateTimeRequest) GetRouterId() int64 {
	if x != nil {
		return x.RouterId
	}
	return 0
}

type CreateTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Seconds    int64  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	RouterId   int64  `protobuf:"varint,3,opt,name=routerId,proto3" json:"routerId,omitempty"`
}

func (x *CreateTimeResponse) Reset() {
	*x = CreateTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeResponse) ProtoMessage() {}

func (x *CreateTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeResponse.ProtoReflect.Descriptor instead.
func (*CreateTimeResponse) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTimeResponse) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *CreateTimeResponse) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *CreateTimeResponse) GetRouterId() int64 {
	if x != nil {
		return x.RouterId
	}
	return 0
}

type TimeSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress   string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Seconds      int64  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	BreaksJson   string `protobuf:"bytes,3,opt,name=breaksJson,proto3" json:"breaksJson,omitempty"`
	Date         string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	SecondsStart int64  `protobuf:"varint,5,opt,name=secondsStart,proto3" json:"secondsStart,omitempty"`
	SecondsEnd   int64  `protobuf:"varint,6,opt,name=secondsEnd,proto3" json:"secondsEnd,omitempty"`
}

func (x *TimeSummary) Reset() {
	*x = TimeSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSummary) ProtoMessage() {}

func (x *TimeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSummary.ProtoReflect.Descriptor instead.
func (*TimeSummary) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSummary) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *TimeSummary) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *TimeSummary) GetBreaksJson() string {
	if x != nil {
		return x.BreaksJson
	}
	return ""
}

func (x *TimeSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimeSummary) GetSecondsStart() int64 {
	if x != nil {
		return x.SecondsStart
	}
	return 0
}

func (x *TimeSummary) GetSecondsEnd() int64 {
	if x != nil {
		return x.SecondsEnd
	}
	return 0
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetTimeSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters []*Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *GetTimeSummaryRequest) Reset() {
	*x = GetTimeSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSummaryRequest) ProtoMessage() {}

func (x *GetTimeSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetTimeSummaryRequest) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{4}
}

func (x *GetTimeSummaryRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetTimeSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeSummary []*TimeSummary `protobuf:"bytes,1,rep,name=timeSummary,proto3" json:"timeSummary,omitempty"`
}

func (x *GetTimeSummaryResponse) Reset() {
	*x = GetTimeSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSummaryResponse) ProtoMessage() {}

func (x *GetTimeSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetTimeSummaryResponse) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{5}
}

func (x *GetTimeSummaryResponse) GetTimeSummary() []*TimeSummary {
	if x != nil {
		return x.TimeSummary
	}
	return nil
}

var File_aggregatorsvc_proto protoreflect.FileDescriptor

var file_aggregatorsvc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x76, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61,
	0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x6a, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0xbf, 0x01, 0x0a,
	0x0b, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x73,
	0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x64, 0x22, 0x30,
	0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x3a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x48, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x32, 0x86, 0x01, 0x0a, 0x0a, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aggregatorsvc_proto_rawDescOnce sync.Once
	file_aggregatorsvc_proto_rawDescData = file_aggregatorsvc_proto_rawDesc
)

func file_aggregatorsvc_proto_rawDescGZIP() []byte {
	file_aggregatorsvc_proto_rawDescOnce.Do(func() {
		file_aggregatorsvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_aggregatorsvc_proto_rawDescData)
	})
	return file_aggregatorsvc_proto_rawDescData
}

var file_aggregatorsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aggregatorsvc_proto_goTypes = []interface{}{
	(*CreateTimeRequest)(nil),      // 0: CreateTimeRequest
	(*CreateTimeResponse)(nil),     // 1: CreateTimeResponse
	(*TimeSummary)(nil),            // 2: TimeSummary
	(*Filter)(nil),                 // 3: Filter
	(*GetTimeSummaryRequest)(nil),  // 4: GetTimeSummaryRequest
	(*GetTimeSummaryResponse)(nil), // 5: GetTimeSummaryResponse
}
var file_aggregatorsvc_proto_depIdxs = []int32{
	3, // 0: GetTimeSummaryRequest.filters:type_name -> Filter
	2, // 1: GetTimeSummaryResponse.timeSummary:type_name -> TimeSummary
	0, // 2: Aggregator.CreateTime:input_type -> CreateTimeRequest
	4, // 3: Aggregator.GetTimeSummary:input_type -> GetTimeSummaryRequest
	1, // 4: Aggregator.CreateTime:output_type -> CreateTimeResponse
	5, // 5: Aggregator.GetTimeSummary:output_type -> GetTimeSummaryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aggregatorsvc_proto_init() }
func file_aggregatorsvc_proto_init() {
	if File_aggregatorsvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aggregatorsvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aggregatorsvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregatorsvc_proto_goTypes,
		DependencyIndexes: file_aggregatorsvc_proto_depIdxs,
		MessageInfos:      file_aggregatorsvc_proto_msgTypes,
	}.Build()
	File_aggregatorsvc_proto = out.File
	file_aggregatorsvc_proto_rawDesc = nil
	file_aggregatorsvc_proto_goTypes = nil
	file_aggregatorsvc_proto_depIdxs = nil
}
