// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: aggregatorsvc.proto

package aggregatorsvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Seconds    int64  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	RouterId   int64  `protobuf:"varint,3,opt,name=routerId,proto3" json:"routerId,omitempty"`
}

func (x *CreateTimeRequest) Reset() {
	*x = CreateTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeRequest) ProtoMessage() {}

func (x *CreateTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeRequest.ProtoReflect.Descriptor instead.
func (*CreateTimeRequest) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTimeRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *CreateTimeRequest) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *CreateTimeRequest) GetRouterId() int64 {
	if x != nil {
		return x.RouterId
	}
	return 0
}

type CreateTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Seconds    int64  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	RouterId   int64  `protobuf:"varint,3,opt,name=routerId,proto3" json:"routerId,omitempty"`
}

func (x *CreateTimeResponse) Reset() {
	*x = CreateTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeResponse) ProtoMessage() {}

func (x *CreateTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeResponse.ProtoReflect.Descriptor instead.
func (*CreateTimeResponse) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTimeResponse) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *CreateTimeResponse) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *CreateTimeResponse) GetRouterId() int64 {
	if x != nil {
		return x.RouterId
	}
	return 0
}

type TimeSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress   string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Seconds      int64  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	BreaksJson   string `protobuf:"bytes,3,opt,name=breaksJson,proto3" json:"breaksJson,omitempty"`
	Date         string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	SecondsStart int64  `protobuf:"varint,5,opt,name=secondsStart,proto3" json:"secondsStart,omitempty"`
	SecondsEnd   int64  `protobuf:"varint,6,opt,name=secondsEnd,proto3" json:"secondsEnd,omitempty"`
}

func (x *TimeSummary) Reset() {
	*x = TimeSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSummary) ProtoMessage() {}

func (x *TimeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSummary.ProtoReflect.Descriptor instead.
func (*TimeSummary) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSummary) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *TimeSummary) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *TimeSummary) GetBreaksJson() string {
	if x != nil {
		return x.BreaksJson
	}
	return ""
}

func (x *TimeSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimeSummary) GetSecondsStart() int64 {
	if x != nil {
		return x.SecondsStart
	}
	return 0
}

func (x *TimeSummary) GetSecondsEnd() int64 {
	if x != nil {
		return x.SecondsEnd
	}
	return 0
}

type GetTimeSummaryByDateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Date       string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetTimeSummaryByDateRequest) Reset() {
	*x = GetTimeSummaryByDateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeSummaryByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSummaryByDateRequest) ProtoMessage() {}

func (x *GetTimeSummaryByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSummaryByDateRequest.ProtoReflect.Descriptor instead.
func (*GetTimeSummaryByDateRequest) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimeSummaryByDateRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *GetTimeSummaryByDateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetTimeSummaryByDateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeSummary *TimeSummary `protobuf:"bytes,1,opt,name=timeSummary,proto3" json:"timeSummary,omitempty"`
}

func (x *GetTimeSummaryByDateResponse) Reset() {
	*x = GetTimeSummaryByDateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregatorsvc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeSummaryByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSummaryByDateResponse) ProtoMessage() {}

func (x *GetTimeSummaryByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregatorsvc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSummaryByDateResponse.ProtoReflect.Descriptor instead.
func (*GetTimeSummaryByDateResponse) Descriptor() ([]byte, []int) {
	return file_aggregatorsvc_proto_rawDescGZIP(), []int{4}
}

func (x *GetTimeSummaryByDateResponse) GetTimeSummary() *TimeSummary {
	if x != nil {
		return x.TimeSummary
	}
	return nil
}

var File_aggregatorsvc_proto protoreflect.FileDescriptor

var file_aggregatorsvc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x76, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61,
	0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x6a, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0xbf, 0x01, 0x0a,
	0x0b, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x73,
	0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x64, 0x22, 0x51,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x4e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x32, 0x98, 0x01, 0x0a, 0x0a, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x1c, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x42, 0x79,
	0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x76, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aggregatorsvc_proto_rawDescOnce sync.Once
	file_aggregatorsvc_proto_rawDescData = file_aggregatorsvc_proto_rawDesc
)

func file_aggregatorsvc_proto_rawDescGZIP() []byte {
	file_aggregatorsvc_proto_rawDescOnce.Do(func() {
		file_aggregatorsvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_aggregatorsvc_proto_rawDescData)
	})
	return file_aggregatorsvc_proto_rawDescData
}

var file_aggregatorsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aggregatorsvc_proto_goTypes = []interface{}{
	(*CreateTimeRequest)(nil),            // 0: CreateTimeRequest
	(*CreateTimeResponse)(nil),           // 1: CreateTimeResponse
	(*TimeSummary)(nil),                  // 2: TimeSummary
	(*GetTimeSummaryByDateRequest)(nil),  // 3: GetTimeSummaryByDateRequest
	(*GetTimeSummaryByDateResponse)(nil), // 4: GetTimeSummaryByDateResponse
}
var file_aggregatorsvc_proto_depIdxs = []int32{
	2, // 0: GetTimeSummaryByDateResponse.timeSummary:type_name -> TimeSummary
	0, // 1: Aggregator.CreateTime:input_type -> CreateTimeRequest
	3, // 2: Aggregator.GetTimeSummaryByDate:input_type -> GetTimeSummaryByDateRequest
	1, // 3: Aggregator.CreateTime:output_type -> CreateTimeResponse
	4, // 4: Aggregator.GetTimeSummaryByDate:output_type -> GetTimeSummaryByDateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aggregatorsvc_proto_init() }
func file_aggregatorsvc_proto_init() {
	if File_aggregatorsvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aggregatorsvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeSummaryByDateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregatorsvc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeSummaryByDateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aggregatorsvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregatorsvc_proto_goTypes,
		DependencyIndexes: file_aggregatorsvc_proto_depIdxs,
		MessageInfos:      file_aggregatorsvc_proto_msgTypes,
	}.Build()
	File_aggregatorsvc_proto = out.File
	file_aggregatorsvc_proto_rawDesc = nil
	file_aggregatorsvc_proto_goTypes = nil
	file_aggregatorsvc_proto_depIdxs = nil
}
